//
// Created by simon on 01/12/2022.
//

#ifndef PROVA1ESAMELABORATORIO_COLLEZIONENOTE_H
#define PROVA1ESAMELABORATORIO_COLLEZIONENOTE_H


class CollezioneNote {

};


#endif //PROVA1ESAMELABORATORIO_COLLEZIONENOTE_H
