//
// Created by simon on 01/12/2022.
//

#ifndef PROVA1ESAMELABORATORIO_COLLEZIONENOTEIMPORTANTI_H
#define PROVA1ESAMELABORATORIO_COLLEZIONENOTEIMPORTANTI_H


class CollezioneNoteImportanti {

};


#endif //PROVA1ESAMELABORATORIO_COLLEZIONENOTEIMPORTANTI_H
